# Generated by Django 5.1.1 on 2024-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cut_sewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='cutting_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='cutting_price_raw',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='length_of_layers',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='model_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='sewing_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='sewing_price_raw',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
