# Generated by Django 5.1.1 on 2024-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cut_cutting_price_alter_cut_cutting_price_raw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='lai_per_unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='product_per_layer',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='length',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
