# Generated by Django 5.1.1 on 2024-10-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cut_lai_per_unit_alter_cut_product_per_layer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'Free'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='type_fabric',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
