# Generated by Django 5.1.1 on 2024-10-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cut_create_date_alter_cut_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producer'),
        ),
    ]
