# Generated by Django 5.1.1 on 2024-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cut_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='layers',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='length',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='products',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
