# Generated by Django 5.1.1 on 2024-10-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_roll_color_alter_roll_layers_alter_roll_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='create_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
