# Generated by Django 5.1.1 on 2024-10-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cut_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='cut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='core.cut'),
        ),
    ]
