# Generated by Django 5.1.1 on 2024-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_roll_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
