# Generated by Django 5.1.1 on 2024-10-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_roll_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='layers',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='length',
            field=models.FloatField(null=True),
        ),
    ]
