# Generated by Django 5.1.1 on 2024-10-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_roll_layers_alter_roll_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='length_of_layers',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
